language: node_js
node_js:
  - "10"
branches:
  only:
  - master
script:
  - npm install
  - npm run build
before_deploy:
  - rm -rf node_modules/ src/
  - rm package.json package-lock.json webpack.config.js
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "acrylminer.com"
  skip_cleanup: true
  region: eu-central-1
  on:
    branch: master